apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: office-management
  labels:
    app: office-backend
spec:
  type: ClusterIP
  selector:
    app: office-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
