apiVersion: v1
kind: ConfigMap
metadata:
  name: office-app-config
  namespace: office-management
data:
  PORT: "5000"
  NODE_ENV: "production"
  CLIENT_URL: "http://office.local"
  VITE_API_URL: "/api"
