apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - mongodb-service.yaml
  - mongodb-statefulset.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: novastore
  app.kubernetes.io/part-of: novastore-platform
  app.kubernetes.io/version: "1.0.0"
