apiVersion: v1
kind: Secret
metadata:
  name: office-app-secrets
  namespace: office-management
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://arvindpatil9206_db_user:UyN82HakA8VMbHs2@cluster0.6r4lbcg.mongodb.net/office_resource_db?retryWrites=true&w=majority"
  JWT_SECRET: "Rq^Qo84(^h6b1i>D|2jD,5Rvbt.{?he]mdyeyc9z-H="
