apiVersion: v1
kind: Secret
metadata:
  name: office-app-secrets
  namespace: office-management
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://<username>:<password>@cluster0.mongodb.net/office_resource_db?retryWrites=true&w=majority"
  JWT_SECRET: "your_production_jwt_secret_key_change_me"
